[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson @ ^6.21.3
  knolleary/PubSubClient @ ^2.8
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  adafruit/Adafruit NeoPixel @ ^1.12.0
